openapi: 3.0.3
info:
  title: Users API
  version: 0.1.0
servers:
  - url: http://localhost:8080
paths:
  /users:
    get:
      summary: Returns a list of users.
      tags:
        - Users
      responses:
        200:
          description: An array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /users/{userId}:
    get:
      summary: Returns a list of users.
      tags:
        - Users
      parameters:
        - name: userId
          in: path
          schema:
            type: string
            format: uuid
          required: true
      responses:
        200:
          description: A user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      x-sample-key: x-sample-key-value
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: John Doe
      required:
        - id
        - name
